oasis-open/cti-stix-elevator

stix2elevator/convert_stix.py

Enhancement to pull request #54. A problem caused by trying to apply a marking to objects that don't exist yet and the elevator would exhaustively convert that marking or identity.

Fix recursion problem in marking and identity creation.

---

stix2elevator/utils.py

Re-create the logger for each call to elevate_X()...

Fix logger setup

---

scripts/json_generator.py
scripts/xml_runner.py
stix2elevator/utils.py

Related to merge request #57 . This should prevent the logger to output messages to multiple log files.

Make sure to remove old file handlers in logger.

---

.gitignore
.isort.cfg
.pre-commit-config.yaml
.travis.yml
README.rst
requirements.txt
setup.cfg
setup.py
stix2elevator/__init__.py
stix2elevator/cli.py
stix2elevator/convert_cybox.py
stix2elevator/convert_pattern.py
stix2elevator/convert_stix.py
stix2elevator/ids.py
stix2elevator/options.py
stix2elevator/test/test_idioms.py
stix2elevator/utils.py
tox.ini

Some functionality to add to the project. This should help in maintaining good quality of the code across all CTI repos.

Add codecov and git hooks configuration.

---

stix2elevator/__init__.py

This is an update to #65 which incorporates the latest additions to master. The build failures for #65 were unrelated to the changes in that branch, so this should fix those.

1 support silent option in validator

---

stix2elevator/__init__.py

Is the same change as in [https://github.com/oasis-open/cti-stix-elevator/pull/61](url).

Add support for Validator silence option

---

.isort.cfg
.travis.yml
README.rst
stix2elevator/__init__.py
stix2elevator/convert_cybox.py
stix2elevator/convert_pattern.py
stix2elevator/convert_stix.py
stix2elevator/ids.py
stix2elevator/options.py
stix2elevator/utils.py
tox.ini

I decided to remove a bunch of "import *" which caused a lot of problem rewriting values.
- Dropped support for Python 2.6
- Fix logger. Also, make sure we print the logger name, if someone wants to disable it.

Update Tox configuration and and fix logging problem

---

stix2elevator/utils.py

Use the class name as identifying information

---

README.rst

- fix dead link
- s:python-stix2:stix2:g
- use new pypi site
- s:pypi.python.org/pypi:pypi.org/project

fix dead link

---

idioms-json/campaign-v-actors.json
idioms-xml/campaign-v-actors.xml
stix2elevator/convert_stix.py

Fix campaign alias.

---

idioms-json/cve-in-exploit-target.json
idioms-xml/cve-in-exploit-target.xml
stix2elevator/convert_pattern.py
stix2elevator/convert_stix.py

cvss_score and affected_software will remain unimplemented unless it is specifically asked for.

For issue #41

---

idioms-json-2.0-valid/141-TLP-marking-structures.json
idioms-json-2.0/141-TLP-marking-structures.json
idioms-json-2.1-valid/141-TLP-marking-structures.json
idioms-json-2.1/141-TLP-marking-structures.json
idioms-xml/141-TLP-marking-structures.xml
stix2elevator/convert_stix.py

Changes suggested by @rpiazza. The suggestion was to remove the TLP markings from the final bundle.

TLP markings changes

---

.isort.cfg
.pre-commit-config.yaml
.travis.yml
scripts/xml_runner.py
stix2elevator/__init__.py
stix2elevator/convert_cybox.py
stix2elevator/convert_pattern.py
stix2elevator/convert_stix.py
stix2elevator/test/test_idioms.py
stix2elevator/test/test_stepper.py
stix2elevator/utils.py
tox.ini

change `iterpath()` method to enumerate values in list

---

stix2elevator/convert_stix.py

Reverts oasis-open/cti-stix-elevator#177

Revert "Threat Actor goals should be a list"

---

scripts/json_generator.py
scripts/xml_runner.py
stix2elevator/__init__.py
stix2elevator/cli.py
stix2elevator/test/test_idioms.py
stix2elevator/test/test_main.py
tox.ini

Adds new elevate() method that encompasses the functionality of all three other functions.
- Deprecate other methods with the intention of removing them in the next major release.
- Added tests for the main methods used to interact with the elevator.

Elevate refactor

---

stix2elevator/__init__.py
stix2elevator/convert_stix.py

issue #182

---

stix2elevator/ids.py

Related #186 
It was just a matter of updating the logic (most of the code was commented) and handle the case with special characters.

Update Deterministic ID generation logic

---

idioms-json-2.0-custom/sighting.json
idioms-json-2.0/sighting.json
idioms-json-2.1-custom/sighting.json
idioms-json-2.1/sighting.json
idioms-xml/sighting.xml
stix2elevator/convert_stix.py

sightings bug

---

idioms-json-2.0-custom/empty-confidence.json
idioms-json-2.0/empty-confidence.json
idioms-json-2.1-custom/empty-confidence.json
idioms-json-2.1/empty-confidence.json
idioms-xml/empty-confidence.xml
stix2elevator/confidence.py
stix2elevator/convert_stix.py
stix2elevator/missing_policy.py

additional changes for PR 199

---

.isort.cfg
scripts/json_generator.py
scripts/xml_runner.py
setup.py
stix2elevator/__init__.py
stix2elevator/cli.py
stix2elevator/confidence.py
stix2elevator/convert_cybox.py
stix2elevator/convert_pattern.py
stix2elevator/convert_stix.py
stix2elevator/ids.py
stix2elevator/missing_policy.py
stix2elevator/options.py
stix2elevator/stix_stepper.py
stix2elevator/test/test_idioms.py
stix2elevator/test/test_main.py
stix2elevator/test/test_stepper.py
stix2elevator/test/test_utils.py
stix2elevator/utils.py

update package to exclude tests and update and apply .isort.cfg
closes #139

Update package settings

---

stix2elevator/convert_stix.py

In Python 3, `etree.tostring` returns a byte string. This causes the following error when elevating STIX content with an OpenIOCTestMechanism:
```
File ".../cti-stix-elevator/stix2elevator/convert_stix.py", line 1911, in finalize_bundle
if final_pattern.contains_placeholder():
AttributeError: 'bytes' object has no attribute 'contains_placeholder'
```
Sample STIX 1.2:
```
<stix:STIX_Package 
xmlns:stix-openioc="http://stix.mitre.org/extensions/TestMechanism#OpenIOC2010-1"
xmlns:stixCommon="http://stix.mitre.org/common-1"
xmlns:stix="http://stix.mitre.org/stix-1"
xmlns:ttp="http://stix.mitre.org/TTP-1"
xmlns:indicator="http://stix.mitre.org/Indicator-2"
xmlns:cyboxCommon="http://cybox.mitre.org/common-2"
xmlns:example="http://example.com" …
```

Ensure OpenIOCTestMechanism byte string is converted to text

---

docs/cyber-observables.rst
docs/warnings.rst
idioms-json-2.0-custom/file-hash-reputation-observable.json
idioms-json-2.0-custom/file-hash-reputation-pattern.json
idioms-json-2.0/file-hash-reputation-observable.json
idioms-json-2.0/file-hash-reputation-pattern.json
idioms-json-2.1-custom/file-hash-reputation-observable.json
idioms-json-2.1-custom/file-hash-reputation-pattern.json
idioms-json-2.1/file-hash-reputation-observable.json
idioms-json-2.1/file-hash-reputation-pattern.json
idioms-xml/archive-file.xml
idioms-xml/file-hash-reputation-observable.xml
idioms-xml/file-hash-reputation-pattern.xml
idioms-xml/file-hash-reputation.xml
idioms-xml/resolve_to_observable.xml
stix2elevator/common.py
stix2elevator/convert_cybox.py
stix2elevator/convert_pattern.py
stix2elevator/options.py

added pdf and image file processing

add file-exts

---

idioms-json-2.0-custom/email-links-observable.json
idioms-json-2.0-custom/malicious-email-indicator-with-addresses.json
idioms-json-2.0/email-links-observable.json
idioms-json-2.0/malicious-email-indicator-with-addresses.json
idioms-json-2.1-custom/email-links-observable.json
idioms-json-2.1-custom/malicious-email-indicator-with-addresses.json
idioms-json-2.1/email-links-observable.json
idioms-json-2.1/malicious-email-indicator-with-addresses.json
idioms-xml/malicious-email-indicator-with-addresses.xml
stix2elevator/convert_cybox.py
stix2elevator/convert_pattern.py

remove observed_data relationships they are related to patterns
handle message body of http request in patterns
class mapping of uri is to url

message_id is a direct property of email-message

---

stix2elevator/test/test_idioms.py

This is a change for the test harness and the output given back (piped to stderr). The AssertionErrors will be printed as an array
```
Checking - C:\Users\cti-stix-elevator\idioms-xml\141-TLP-marking-structures.xml
With Master - bundle--88139233-3c7d-4913-bb5e-d2aeb079d029
Results produced by the stix2-elevator are not for production purposes.
{
"id": "bundle--88139233-3c7d-4913-bb5e-d2aeb079d029",
"objects": [
{
"created": "2014-05-08T09:00:00.000Z",
"id": "indicator--8a822399-5d8a-44e4-abeb-15d480ea93c5",
"indicator_types": [
"url-watchlist"
],
"modified": "2014-05-08T09:00:00.000Z",
"name": "Malicious site hosting downloader",
"object_marking_refs": [
"marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
],
"pattern": "[url:value = 'http://x4z9arb.cn/4712']",
"pattern_type": …
```

Capture all AssertionErrors from a single file run

---

stix2elevator/common.py
stix2elevator/convert_cybox.py
stix2elevator/convert_pattern.py
stix2elevator/test/test_idioms.py

Brings stability to generated pattern and 'pdf-ext' observable extension.

PDF-Ext Fix

---

stix2elevator/options.py
stix2elevator/test/test_idioms.py

looks like the options weren't set yet but decisions were made as if they were during testing

Default 2.1

---

stix2elevator/convert_pattern.py
stix2elevator/convert_to_acs.py

- Added additional data validation by checking for the existence of the authority_reference dictionary key
- Ensuring that the prop.layer4_protocol.value has data and not just that the object exists

Add additional data validation logic
